BoxLayout
    orientation: 'vertical'
    BoxLayout:
        orientation: 'horizontal'
        TextInput
            id: input_miles
            text: 'Miles'
            font_size: 40
        BoxLayout:
            orientation: 'vertical'
            Button:
                text: 'Up'
            Button:
                text: 'Down'
    Label:
        id: output_label
        font_size: 30
        text: 'Kilometres'
        color: (1, 1, 0, 1)

